/*

 */
package eva3_3_trycatch;


public class EVA3_3_TRYCATCH {


    public static void main(String[] args) {
     int x=5, y =0;
     
  try {
      //Secci贸n de c贸digo que genera una excepci贸n
      
     int resu = x/y;
        System.out.println("Resultado: "+resu);
  } catch (ArithmeticException e){
      //Se genera un objeto "e"
      
        System.out.println("Excepci贸n: " +e.getMessage());   
      }
        System.out.println("Fin del programa.");
        
    }
    
    
}
